### PR TITLE
Improve Dockerfile build

### PR DESCRIPTION
**Pull request by Taucher2003**
This splits the contents of the built image into multiple layers to reduce the size of each layer

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
Why not use the application plugin and make a dist?

**Comment by Taucher2003** [comment]
> Why not use the application plugin and make a dist?

Because that puts all dependency jars and the jar itself into a tar/zip archive and not into one jar that can be extracted to split them into multiple layers

**Comment by DRSchlaubi** [comment]
> > Why not use the application plugin and make a dist?
> 
> Because that puts all dependency jars and the jar itself into a tar/zip archive and not into one jar that can be extracted to split them into multiple layers

What's the point of building one jar and then extract all libs out of that jar, if Gradle has a feature to extract all libs into a folder

**Comment by Taucher2003** [comment]
> > > Why not use the application plugin and make a dist?
> > 
> > 
> > Because that puts all dependency jars and the jar itself into a tar/zip archive and not into one jar that can be extracted to split them into multiple layers
> 
> What's the point of building one jar and then extract all libs out of that jar, if Gradle has a feature to extract all libs into a folder

We don't want them as jar, because we copy the folders with the classes itself into the Docker image to reduce the image size by splitting it into multiple layers because they can be reused every time until something changes in the specific layer

**Review by RainbowDashLabs — COMMENTED** [review]
I really dont know what to say xD
As long as it works I am fine xD
I am lacking the actual knowledge about docker in this case and would trust @yannicklamprecht on this :D

**Review by yannicklamprecht — APPROVED** [review]
After minimizing the image by using a slimmer base image and rm all file in **extract dependencies** stage using one layer. I'm fine with it.

**Pull request merged**
