### PR TITLE
Implement docker image deployment

### PR DESCRIPTION
**Pull request by Taucher2003**
Relates to #210 

This is the fourth part of improving the Docker setup.
This one adds the image deployment to the container registry

### CODE REVIEW

**Comment by RainbowDashLabs** [comment]
Dont we wanna only deploy on a master push? Might be better instead of deploying on every push

**Comment by Taucher2003** [comment]
The current setup would push the image for master, development and tags. The `latest` tag always points to master. But this way would give selfhosted users the possibility to use the development branch, if they want.

What is @yannicklamprecht opinion on this?

**Comment by RainbowDashLabs** [comment]
One suggestion from my side would also be to use move the deployment to an extra workflow and not inside the verify.
The verify workflow should be for the pure verification of integrity.

I would also suggest to make two different tasks in this workflow for latest and dev builds and use the integrated branch paramter for workflows to make it more readable

```
  tag:
  push:
    branches:
      - main
      - dev
```

**Comment by RainbowDashLabs** [comment]
One more addition.

Our current stable branch is called "master" and not "main". I am open to align to the new main paradigm, but currently the workflow would never publish a latest release

**Comment by yannicklamprecht** [comment]
> The current setup would push the image for master, development and tags. The `latest` tag always points to master. But this way would give selfhosted users the possibility to use the development branch, if they want.
> 
> What is @yannicklamprecht opinion on this?


Just have multiple latest images.

-latest-dev
-latest-stable

**Comment by Taucher2003** [comment]
> > The current setup would push the image for master, development and tags. The `latest` tag always points to master. But this way would give selfhosted users the possibility to use the development branch, if they want.
> > What is @yannicklamprecht opinion on this?
> 
> Just have multiple latest images.
> 
> -latest-dev 
> -latest-stable

There are images with the branch name, `development` would be equal to your suggested `latest-dev` and `master` would be equal to `latest`. `latest` itself is just for Docker, as it searches for this tag if no tag was given

**Review by RainbowDashLabs — APPROVED** [review]

**Comment by Taucher2003** [comment]
Blocked by #234

**Review by yannicklamprecht — APPROVED** [review]

**Pull request merged**
